### PR TITLE
fix `cross-origin` iframe and no parent debugbar

### LINKED ISSUE #650: Debugbar not showing in embed iframe
Hello, i'm devloping Shopify Apps under Laravel framework, which is using php-debugbar package

Because of this line, we cannot print the debug bar : 

https://github.com/maximebf/php-debugbar/blob/cd46685df82a370f6682ad92a81adfc44326f438/src/DebugBar/Resources/debugbar.js#L428

The concept of shopify apps is really simple : embed apps into an iframe, so it makes it completely incompatible with the debug bar, and generates the following error : 

```
Uncaught DOMException: Failed to read a named property 'phpdebugbar' from 'Window': Blocked a frame with origin "https://[subdomain].ngrok-free.app" from accessing a cross-origin frame.
    at child.addDataSet (https://[subdomain].ngrok-free.app/_debugbar/assets/javascript?v=1712740545:949:28)
    at https://[subdomain].ngrok-free.app/admin/dashboard?shop=[subdomain].myshopify.com&host=[...]:633:13
```

What should we do ?

### PR DESCRIPTION
**Pull request by erikn69**
Closes #650
```
Failed to read a named property 'phpdebugbar' from 'Window': 
Blocked a frame with origin "https://[subdomain].ngrok-free.app" from accessing a cross-origin frame.
    at child.addDataSet (https://[subdomain].ngrok-free.app/_debugbar/assets/javascript?v=1712740545:949:28)
    at https://[subdomain].ngrok-free.app/admin/dashboard?shop=[subdomain].myshopify.com&host=[...]:633:13
```

### CODE REVIEW

**Review by jose123v — APPROVED** [review]

File: src/DebugBar/Resources/debugbar.js [hunk 1]
```diff
@@ -425,7 +425,9 @@ if (typeof(PhpDebugBar) == 'undefined') {
             this.activeDatasetId = null;
             this.datesetTitleFormater = new DatasetTitleFormater(this);
             this.options.bodyMarginBottomHeight = parseInt($('body').css('margin-bottom'));
-            this.isIframe = window.self !== window.top;
+            try {
+                this.isIframe = window.self !== window.top && window.top.phpdebugbar;
+            } catch (error) {}
```
Comment (barryvdh) [inline src/DebugBar/Resources/debugbar.js:430]: Should the catch set the variable to false?

Comment (erikn69) [reply src/DebugBar/Resources/debugbar.js]: I did add it
but by default wouldn't it be `undefined`? 
And a conditional on `undefined` results in `false`, right?
